### ISSUE TITLE
Morning-code review 

### ISSUE THREAD

**Issue by imubarak234** [thecodechaser/portfolio-bootstrap#2]
Very good use of Bootstrap. It's nice to see the responsiveness of the website.

**Comment by thecodechaser** [comment]
> Very good use of Bootstrap. It's nice to see the responsiveness of the website.

Hii @imubarak234

Thank you for your feedback, This will really motivate me to keep things up. 👍

**Comment by mugishasam123** [comment]
great work but try to add background color

**Comment by HaseebSediqi** [comment]
Great job! 👍 
Customized very well. 
Keep up this great work. 😄

**Comment by thecodechaser** [comment]
> great work but try to add background-color

Hii @mugishasam123 

Thank you for your feedback, In project requirements, it is not necessary to make the website exactly as Figma template but your suggestion is good this will make my website look more good, I will definitely work on that. 👍

**Comment by thecodechaser** [comment]
> Great job! 👍 Customized very well. Keep up this great work. 😄

Hii @HaseebSediqi 

Thank you for your feedback. This will help me to work hard more 👍
